# CICD using GitHub actions

name: CI/CD

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches: [main]
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  golangci:
    name: Run GolangCI-Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  sonarcloud:
    name: Perform SonarCloud Scan
    runs-on: ubuntu-latest

    needs: golangci

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3.1.0
        with:
          args: "-Dsonar.projectKey=cybermazi_golang-todo-app -Dsonar.organization=cybermazi"
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          

  build:
    name: Build Application
    runs-on: ubuntu-latest

    needs: sonarcloud

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Build
      run: go build -o golang-todo-app
  
  push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t takalezi6/golang-todo-app:${{ github.run_id }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker image
      run: docker push takalezi6/golang-todo-app:${{ github.run_id }}
    
  update-newtag-in-helm-chart:
    name: Update Helm Chart with New Tag
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/golang-todo-app-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "takalezi6@gmail.com"
        git config --global user.name "Akalezi Caleb"
        git add helm/golang-todo-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push